---

- name: Setup sysctl configuration
  sysctl:
    name: '{{item.name}}'
    value: '{{ item.value|default(None) }}'
    ignoreerrors: '{{ item.ignoreerrors|default(False) }}'
    reload: '{{ item.reload|default(True) }}'
    state: '{{ item.state|default("present") }}'
    sysctl_file: '{{ item.sysctl_file|default("/etc/sysctl.d/ansible.conf") }}'
    sysctl_set: '{{ item.sysctl_set|default(False) }}'
  with_items: procps_values
  when: procps_values is defined
    
